<section class="banner about_banner">
    <div>
        <h2>QUI SOMMES NOUS?</h2>
        <div class="bloc">
            <p><em>Maison B c'est l'histoire d'une famille qui se transmet de génération en génération depuis les années 60. Tradition, savoir faire et artisanat ont fait notre renommée.</em></p>
            <div class="button"><a href="?action=contactUs">Nous contacter</a></div>
        </div>
    </div>
    <img id="sliderright3" class="img_right" src="../src/img/equipe/equipe1.jpg" alt="photo de la boulangerie dans les années 60.">
</section>
<hr>
<section class="article2">
    <div>
        <h3>Faites notre connaissance</h3>
        <p>Depuis les années 60, Maison B a fait du chemin et à évoluée au fil du temps. Plus que des collègues, nous sommes une famille dédiée entierement à la vision qualitative de la boulangerie. Nos chefs dispose d’importants moyens techniques pour pouvoir répondre à la demande de nos clients. Plusieurs milliers de créations sortent chaque jour de notre atelier !</p>
        <p><strong>Découvrez notre belle équipe qui se démène chaque jour pour vous offrir le meilleur !</strong></p>
    </div>
</section>
<section class="gallery">
        <?php foreach($items as $item): ?>
        <figure>
            <img src="<?= $item['url_about'] ?>" alt="<?= $item['description_about'] ?>">
            <figcaption>
                <div><strong><?= $item['name_about'] ?></strong>
                <p><?= $item['profession_about'] ?></p>
                </div>
            </figcaption>
        </figure>
        <?php endforeach ?>
</section>

<section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="?action=contactUs">Nous contacter</a></div>
</section>

