<section class="banner about_banner">
    <div>
        <h2>QUI SOMMES NOUS?</h2>
        <div class="bloc">
            <p><em>Maison B c'est l'histoire d'une famille qui se transmet de génération en génération depuis les années 60. Tradition, savoir faire et artisanat ont fait notre renommée.</em></p>
            <div class="button"><a href="#">Nous contacter</a></div>
        </div>
    </div>
    <img class="img_right" src="../src/img/equipe/equipe1.jpg" alt="photo de la boulangerie dans les années 60.">
</section>
<hr>
<section class="article2">
    <div>
        <h3>Faites notre connaissance</h3>
        <p>Depuis les années 60, Maison B a fait du chemin et à évoluée au fil du temps. Plus que des collègues, nous sommes une famille dédiée entierement à la vision qualitative de la boulangerie. Nos chefs dispose d’importants moyens techniques pour pouvoir répondre à la demande de nos clients. Plusieurs milliers de créations sortent chaque jour de notre atelier !</p>
        <p><strong>Découvrez notre belle équipe qui se démène chaque jour pour vous offrir le meilleur !</strong></p>
    </div>
</section>
<section class="gallery">
        <figure>
            <img src="../src/img/equipe/equipe3.jpg" alt="Mike boulanger en chef chez Maison B">
            <figcaption>
                <div><strong>Mike</strong>
                <p>boulanger en chef</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe4.jpg" alt="Pierre boulanger chez Maison B">
            <figcaption>
                <div><strong>Pierre</strong>
                <p>vendeur comptoir</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe5.jpg" alt="Julien boulanger chez Maison B">
            <figcaption>
                <div><strong>Julien</strong>
                <p>boulanger</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe6.jpg" alt="Marie boulangère chez Maison B">
            <figcaption>
                <div><strong>Marie</strong>
                <p>boulangère</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe7.jpg" alt="Aymeric boulanger/pâtissier chez Maison B">
            <figcaption>
                <div><strong>Aymeric</strong>
                <p>boulanger/pâtissier</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe8.jpg" alt="Aurelie vendeuse chez Maison B">
            <figcaption>
                <div><strong>Aurelie</strong>
                <p>vendeuse</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe9.jpg" alt="Nora Cheffe pâtissière chez Maison B">
            <figcaption>
                <div><strong>Nora</strong>
                <p>Cheffe pâtissière</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe10.jpg" alt="Aissa apprentie pâtissière chez Maison B">
            <figcaption>
                <div><strong>Aissa</strong>
                <p>apprentie pâtissière</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe11.jpg" alt="Djibril boulanger chez Maison B">
            <figcaption>
                <div><strong>Djibril</strong>
                <p>boulanger</p>
                </div>
            </figcaption>
        </figure>
        <figure>
            <img src="../src/img/equipe/equipe12.jpg" alt="Youssouf pâtissier chez Maison B">
            <figcaption>
                <div><strong>Youssouf</strong>
                <p>pâtissier</p>
                </div>
            </figcaption>
        </figure>
</section>

<section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="#">Nous contacter</a></div>
</section>

