<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <section class="banner about_banner">
            <div>
                <h2>QUI SOMMES NOUS?</h2>
                <div class="bloc">
                    <p><em>Maison B c'est l'histoire d'une famille qui se transmet de génération en génération depuis les années 60. Tradition, savoir faire et artisanat ont fait notre renommée.</em></p>
                    <div class="button"><a href="#">Nous contacter</a></div>
                </div>
            </div>
        <div><img class="img_right" src="../src/img/equipe/equipe1.jpg" alt="photo de la boulangerie dans les années 60."></div>
    </section>
    <hr>
    <section class="article2">
        <div>
            <h3>Faites notre connaissance</h3>
            <p>Depuis les années 60, Maison B a fait du chemin et à évoluée au fil du temps. Plus que des collègues, nous sommes une famille dédiée entierement à la vision qualitative de la boulangerie. Nos chefs dispose d’importants moyens techniques pour pouvoir répondre à la demande de nos clients. Plusieurs milliers de créations sortent chaque jour de notre atelier !</p>
            <p><strong>Découvrez notre belle équipe qui se démène chaque jour pour vous offrir le meilleur !</strong></p>
        </div>
    </section>
    <section class="gallery">
            <img src="../src/img/equipe/equipe3.jpg" alt="Mike boulanger en chef chez Maison B">
            <img src="../src/img/equipe/equipe4.jpg" alt="Pierre vendeur chez maison B">
            <img src="../src/img/equipe/equipe5.jpg" alt="Julien boulanger chez Maison B">
            <img src="../src/img/equipe/equipe6.jpg" alt="Marie boulangère chez Maison B">
            <img src="../src/img/equipe/equipe7.jpg" alt="Aymeric boulanger/pâtissier chez Maison B">
            <img src="../src/img/equipe/equipe8.jpg" alt="Aurelie vendeuse chez Maison B">
            <img src="../src/img/equipe/equipe9.jpg" alt="Nora Cheffe pâtissiere chez Maison B">
            <img src="../src/img/equipe/equipe10.jpg" alt="Aissa apprentie pâtissière chez Maison B">
            <img src="../src/img/equipe/equipe11.jpg" alt="Djibril boulanger chez Maison B">
            <img src="../src/img/equipe/equipe12.jpg" alt="Youssouf pâtissier chez Maison B">
    </section>

    <section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="#">Nous contacter</a></div>
</section>
</body>
