<?php if (isset($_SESSION['name'])): ?>
<section class="banner">
            <h2>La Boulangerie</h2>
</section>
<hr>

<section class="admin">
<table>
    <thead>
        <tr>
            <td>Liens des photos</td>
            <td>Description de la photo</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['url_bakery'] ?></td>
            <td><?= $item['description_bakery'] ?></td>
            <td>
                <a href="?action=getBakery&id=<?= $item['id_bakery'] ?>"><i class="bi bi-pencil"></i></a>
                <a href="?action=deleteBakery&id=<?= $item['id_bakery'] ?>"><i class="bi bi-trash"></i></a>
            </td>  
       </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php if ($id=isset($_GET['id']) && !empty($items)): ?>

<form action="?action=updateBakery" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id" value="<?= $item['id_bakery'] ?>">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture" value="<?= $item['url_bakery'] ?>">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description" value="<?= $item['description_bakery'] ?>">
    </div>
    <button type="submit">Modifier</button>
</form>

<?php  elseif($action ='admin' && !empty($items)) : ?>
 
<form action="?action=createBakery" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture"">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description">
    </div>
    <button type="submit">Ajouter</button>
</form>
<?php endif ?>

<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
<?php else: ?>
    <?= header('Location: index.php?action=login') ?>
<?php endif ?>