                                                <!--   CRUD DE L'ONGLET ATELIER -->
<?php if (isset($_SESSION['name'])): ?>
<section class="banner">
    <h2>Les Ateliers</h2>
</section>
<hr>
<!--  READ DU CRUD -->
<section class="admin">
<table>
    <thead>
        <tr>
            <td>Nom de l'atelier</td>
            <td>Date</td>
            <td>Prix</td>
            <td>Liens des photos</td>
            <td>Description de la photo</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['name_pastryClass'] ?></td>
            <td><?= $item['date_pastryClass'] ?></td>
            <td><?= $item['price_pastryClass'] ?></td>
            <td><?= $item['url_pastryClass'] ?></td>
            <td><?= $item['description_pastryClass'] ?></td>
            <td>
                <a href="?action=getPastryClass&id=<?= $item['id_pastryClass'] ?>"><i class="bi bi-pencil"></i></a>
                <!--  DELETE DU CRUD -->
                <a href="?action=deletePastryClass&id=<?= $item['id_pastryClass'] ?>"><i class="bi bi-trash"></i></a>
            </td>  
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php if ($id=isset($_GET['id']) && !empty($items)): ?>
<!--  UPDATE DU CRUD -->
<form action="?action=updatePastryClass" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id" value="<?= $item['id_pastryClass'] ?>">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name" value="<?= $item['name_pastryClass'] ?>">
    </div>
    <div>
        <label for="date">Date:</label>
        <input type="text" id="date" name="date" value="<?= $item['date_pastryClass'] ?>">
    </div>
    <div>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" value="<?= $item['price_pastryClass'] ?>">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture" value="<?= $item['url_pastryClass'] ?>">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description" value="<?= $item['description_pastryClass'] ?>">
    </div>
    <button type="submit">Modifier</button>
</form>

<?php  elseif($action ='admin' && !empty($items)) : ?>
   <!--  CREATE DU CRUD -->
<form action="?action=createPastryClass" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name">
    </div>
    <div>
        <label for="date">Date:</label>
        <input type="text" id="date" name="date">
    </div>
    <div>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description">
    </div>
    <button type="submit">Ajouter</button>
</form>
<?php endif ?>
<!--  Deconnection  -->
<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
<?php else: ?>
    <?= header('Location: index.php?action=login') ?>
<?php endif ?>