                                                <!--   CRUD DE L'ONGLET L'EQUIPE -->
<?php if (isset($_SESSION['name'])): ?>
<section class="banner">
    <h2>L'Équipe Maison B</h2>
</section>
<hr>
<!--  READ DU CRUD -->
<section class="admin">
<table>
    <thead>
        <tr>
            <td>Nom</td>
            <td>Poste</td>
            <td>Liens des photos</td>
            <td>Description de la photo</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['name_about'] ?></td>
            <td><?= $item['profession_about'] ?></td>
            <td><?= $item['url_about'] ?></td>
            <td><?= $item['description_about'] ?></td>
            <td>
                <a href="?action=getTeam&id=<?= $item['id_about'] ?>"><i class="bi bi-pencil"></i></a>
                <!--  DELETE DU CRUD -->
                <a href="?action=deleteTeam&id=<?= $item['id_about'] ?>"><i class="bi bi-trash"></i></a>
            </td>        
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php if ($id=isset($_GET['id']) && !empty($items)): ?>
<!--  UPDATE DU CRUD -->
<form action="?action=updateTeam" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id" value="<?= $item['id_about'] ?>">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name" value="<?= $item['name_about'] ?>">
    </div>
    <div>
        <label for="profession">Poste:</label>
        <input type="text" id="profession" name="profession" value="<?= $item['profession_about'] ?>">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture" value="<?= $item['url_about'] ?>">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description" value="<?= $item['description_about'] ?>">
    </div>
    <button type="submit">Modifier</button>
</form>

<?php  elseif($action ='admin' && !empty($items)) : ?>
<!--  CREATE DU CRUD -->
<form action="?action=createTeam" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id"">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name"">
    </div>
    <div>
        <label for="profession">Poste:</label>
        <input type="text" id="profession" name="profession"">
    </div>
    <div>
        <label for="picture">Photo:</label>
        <input type="text" id="picture" name="picture"">
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description">
    </div>
    <button type="submit">Ajouter</button>
</form>
<?php endif ?>
<!--  Deconnection  -->
<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
<?php else: ?>
    <?= header('Location: index.php?action=login') ?>
<?php endif ?>