
<section class="banner">
            <h2>Administrateurs</h2>
</section>
<hr>
<section class="admin">
<table>
    <thead>
        <tr>
            <td>Nom</td>
            <td>Email</td>
            <td>Mot de passe</td>
            <td>action</td>
        </tr>
    </thead>
    <tbody>
        
        <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['name'] ?></td>
            <td><?= $item['email'] ?></td>
            <td><?= $item['password'] ?></td>
            <td><a href=""><i class="bi bi-pencil"></i></a><a href=""><i class="bi bi-trash"></i></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
