<?php if (isset($_SESSION['name'])): ?>
<section class="banner">
            <h2>Demandes/Renseignements</h2>
</section>
<hr>
<section class="admin">
<table>
    <thead>
        <tr>
            <td>Nom</td>
            <td>Phone</td>
            <td>Email</td>
            <td>Message</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['nameContact'] ?></td>
            <td><?= $item['phoneContact'] ?></td>
            <td><?= $item['mailContact'] ?></td>
            <td><?= $item['messageContact'] ?></td>
            <td><a href="?action=deleteContact&id=<?= $item['id_contact'] ?>"><i class="bi bi-trash"></i></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
<?php else: ?>
    <?= header('Location: index.php?action=login') ?>
<?php endif ?>
