                                            <!--  CRUD DE L'ONGLET ADMIN -->
<?php if (isset($_SESSION['name'])): ?>
<section class="banner">
            <h2>Administrateurs</h2>
</section>
<hr>
<!--  READ DU CRUD -->
<section class="admin">
<table>
    <thead>
        <tr>
            <td>Nom</td>
            <td>Email</td>
            <td>Mot de passe</td>
            <td>action</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item): ?>
        <tr>
            <td><?= $item['name'] ?></td>
            <td><?= $item['email'] ?></td>
            <td><?= password_hash($item['password'], PASSWORD_DEFAULT) ?></td>
            <td>
                <a href="?action=get&id=<?= $item['id_admin'] ?>"><i class="bi bi-pencil"></i></a>
                <!--  DELETE DU CRUD -->
                <a href="?action=delete&id=<?= $item['id_admin'] ?>"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php if ($id=isset($_GET['id']) && !empty($items)): ?>
<!--  UPDATE DU CRUD -->
<form action="?action=update" method="POST">
    <div>
        <label for="id">Id:</label>
        <input type="text" id="id" name="id" value="<?= $item['id_admin'] ?>">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name" value="<?= $item['name'] ?>">
    </div>
    <div>
        <label for="mail">E-mail:</label>
        <input type="email" id="mail" name="mail" value="<?= $item['email'] ?>">
    </div>
    <div>
        <label for="mail">Mot de passe:</label>
        <input type="password" id="password" name="password" value="<?= password_hash($item['password'], PASSWORD_DEFAULT) ?>">
    </div>
    <button type="submit">Modifier</button>
</form>

<?php  elseif($action ='admin' && !empty($items)) : ?>
 <!--  CREATE DU CRUD -->
<form action="?action=create" method="POST">
    <div>
        <label for="name">Id:</label>
        <input type="text" id="id" name="id">
    </div>
    <div>
        <label for="name">Nom:</label>
        <input type="text" id="name" name="name">
    </div>
    <div>
        <label for="mail">E-mail:</label>
        <input type="email" id="mail" name="mail">
    </div>
    <div>
        <label for="mail">Mot de passe:</label>
        <input type="password" id="password" name="password">
    </div>
    <button type="submit">Ajouter</button>
</form>
<?php endif ?>
<!--  Deconnection  -->
<p>N'oubliez pas de vous <a href="?action=logout">Déconnecter</a></p>
</section>
<?php else: ?>
    <?= header('Location: index.php?action=login') ?>
<?php endif ?>
