<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <section class="bakery_banner">
            <div>
                <h2>LA BOULANGERIE</h2>
                <div class="bloc">
                    <p><em>Prendre le meilleur d’un savoir-faire transmis depuis des générations et l’adapter aux attentes et aux goûts d’aujourd’hui, voilà notre philosophie. </em></p>
                    <div class="button"><a href="#">Nous contacter</a></div>
                </div>
            </div>
        <div><img class="img_right" src="../src/img/pain/pain2.png" alt="photo de différents pains"></div>
    </section>
    <hr>
    <section class="article2">
        <div>
            <h3>Découvrez notre gamme</h3>
            <p>Tous nos pains sont fabriqués à partir de céréales issues à 100% de l’agriculture biologique et de farines provenant de moulins situés en Île-de-France. Nos produits sont frais, d’une qualité irréprochable et préparés avec des ingrédients de saison qui apportent toutes leurs saveurs aux recettes originales créées par notre Chef.<br>Découvrez nos produits élaborés spécialement pour vous.</p>
        </div>
    </section>
    <section class="grid">
        
    </section>
</body>
