<section class="banner bakery_banner">
    <div>
        <h2>LA BOULANGERIE</h2>
        <div class="bloc">
            <p><em>Prendre le meilleur d’un savoir-faire transmis depuis des générations et l’adapter aux attentes et aux goûts d’aujourd’hui, voilà notre philosophie. </em></p>
            <div class="button"><a href="#">Nous contacter</a></div>
        </div>
    </div>
    <img class="img_right" src="../src/img/pain/pain17.png" alt="photo de différents pains">
</section>
<hr>
<section class="article2">
    <div>
        <h3>Découvrez notre gamme</h3>
        <p>Tous nos pains sont fabriqués à partir de céréales issues à 100% de l’agriculture biologique et de farines provenant de moulins situés en Île-de-France. Nos produits sont frais, d’une qualité irréprochable et préparés avec des ingrédients de saison qui apportent toutes leurs saveurs aux recettes originales créées par notre Chef.</p>
        <p><strong>Découvrez nos produits élaborés spécialement pour vous.</strong></p>
    </div>
</section>
<section class="grid">

</section>
<section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="?action=contactUs">Nous contacter</a></div>
</section>
