<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <section class="banner">
        <div>
            <div class="bloc">
                <h2>NOUS CONTACTER</h2>
                <p><em>Ouvert tous les jours</em></p>
                <p><em>- de 7h à 21h -</em></p>
            </div>
        </div>
    </section>
    <hr>
    <section class="article2">
        <div>
            <h3>Pour nous contacter remplisser le formulaire </h3>
            <p>N'hésitez pas à nous contacter pour toute question concernant votre Boulangerie Maison B !</p>
            <p><strong>- 126 boulevard Serurier 75019 Paris -</strong></p>
        </div>
    </section>
    <section class="contactUs">
        <form action="" method="POST">
            <div>
                <label for="name">Nom & Prénom:</label>
                <input type="text" id="name" name="name">
            </div>
            <div>
                <label for="phone">Téléphone:</label>
                <input type="tel" id="phone" name="phone">
            </div>
            <div>
                <label for="mail">E-mail:</label>
                <input type="email" id="mail" name="mail">
            </div>
            <div>
                <label for="object-select">Objet:</label>
                <select name="pets" id="pet-select">
                    <option value="0">- Choisir l'objet de votre demande -</option>
                    <option value="1">Emettre un avis</option>
                    <option value="2">Autres demandes ou renseignements</option>
                </select>
            </div>
            <div>
                <label for="msg">Message:</label>
                <textarea id="msg" name="message"></textarea>
            </div>
            <div>
                <button type="submit">Envoyer</button>
            </div>
        </form>
        <hr>
        <div class="address">
            <div>
                <address>
                    <strong>
                        <p>126 boulevard Serurier Paris</p>
                        <p>Ouvert tous les jours </p>
                        <p>de 7h à 21h</p>
                        <p><a href="Maisonb@boulangerie.com">Maisonb@boulangerie.com</a></p>
                        <p><a href="tel:+33142083795">01 42 08 37 95</a></p>
                    </strong>
                </address>
            </div>
            <hr>
            <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d888.224470218659!2d2.3935936208102175!3d48.886690633264976!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66db798b02e25%3A0xc9752a10aaaf59a3!2s126%20Bd%20S%C3%A9rurier%2C%2075019%20Paris!5e0!3m2!1sfr!2sfr!4v1650035628637!5m2!1sfr!2sfr" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                <img src="../src/img/logo_min.png" alt="logo de la boulangerie/pâtisserie" width= "150px">
            </div>
        </div>
    </section>
</body>
