<section class="error">
    <img src="../src/img/error.jpg" alt="un pain de mie avec une clé à molette">
    <h2>Ooopss la page est temporairement inaccessible.</h2>
    <div>
        <p>Notre tech'Mie'cien met tout en oeuvre pour résoudre le problème au plus vite.</p>
        <p>En attendant que tout revienne à la normale, vous pouvez revenir à la <a href="?action=home">Page d'accueil</a> ou nous rendre une petite visite sur <a href="https://fr-fr.facebook.com/">Facebook</a>,  <a href="https://twitter.com/?lang=fr">Twitter</a> ou <a href="https://www.instagram.com/?hl=fr">Instagram</a>.</p>
    </div>
</section>