<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<section class="home_banner">
    <div>
        <h1>Chez Maison B.</h1>
    <p>Un savoir-faire traditionnel et une gamme de produits 100% maison réalisés avec passion à partir de matière première de qualité.</p>
    <p><em>Pour en savoir plus et pour toute commande n'hesitez pas à vous rapprocher de nous !</em></p>
    <div class="button"><a href="#">Nous contacter</a></div>
    </div>
</section>

