<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>
<body>
    <header class="header">
        <a href="#"><img src="../src/img/logo.png" alt="logo de la boulangerie/pâtisserie" width='300px'></a>
        <nav>
            <ul class="navbar">
                <li><a href="">Boulangerie</a></li>
                <li><a href="">Pâtisserie</a></li>
                <li><a href="">Qui sommes nous?</a></li>
                <li><a href="">Contact</a></li>
                <li><a href=""><i class="bi bi-basket"></i></a></li>
            </ul>   
        </nav>
    </header>
    <main>

    </main>
    <footer class="footer">
        <img src="../src/img/logo_min.png" alt="logo de la boulangerie/pâtisserie" width= "150px">
        <hr>
        <div>
            <p>Retrouvez nous sur: </p>
            <a href="https://fr-fr.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            <a href="https://www.instagram.com/?hl=fr" target="_blank"><i class="bi bi-instagram"></i></a>
            <a href="https://twitter.com/?lang=fr" target="_blank"><i class="bi bi-twitter"></i></a>
        </div>
    </footer>    
    
</body>
</html>

