<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha256-UK1EiopXIL+KVhfbFa8xrmAWPeBjMVdvYMYkTAEv/HI=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" integrity="sha256-4hqlsNP9KM6+2eA8VUT0kk4RsMRTeS7QGHIM+MZ5sLY=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha256-NXRS8qVcmZ3dOv3LziwznUHPegFhPZ1F/4inU7uC8h0=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../src/style.css">
</head>

<body>
    <header class="header">
        <a href="?action=home"><img src="../src/img/logo.png" alt="logo de la boulangerie/pâtisserie" width='300px'></a>
        <nav>
            <ul class="navbar">
                <li><a href="?action=bakery">Boulangerie</a></li>
                <li><a href="?action=pastry">Pâtisserie</a></li>
                <li><a href="?action=pastryClass">Nos ateliers</a></li>
                <li><a href="?action=aboutUs">Qui sommes nous?</a></li>
                <li><a href="?action=contactUs">Contact</a></li>
                <li><a href="?action=shoppingCart"><i class="bi bi-basket"></i></a></li>
            </ul>   
        </nav>
    </header>
    <main>
        <?php include $template.'.phtml' ?>
    </main>
    <footer class="footer">
        <img src="../src/img/logo_min.png" alt="logo de la boulangerie/pâtisserie"  class="min">

        <hr>
        <div>
            <p>Retrouvez nous sur: </p>
            <a href="https://fr-fr.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            <a href="https://www.instagram.com/?hl=fr" target="_blank"><i class="bi bi-instagram"></i></a>
            <a href="https://twitter.com/?lang=fr" target="_blank"><i class="bi bi-twitter"></i></a>
        </div>
        <div class="lastBloc">
        <a href="?action=legalDisclaimer">mentions légales</a>
        <a href="?action=admin"><i class="bi bi-lock-fill"></i></a>
        </div>
    </footer>
    <script src="../src/js/jquery.js"></script>
</body>
</html>

