<section class="banner">
    <div>
        <div>
            <img src="../src/img/logo_min.png" alt="logo de la boulangerie/pâtisserie" class="min">
            <h2>LES MENTIONS LÉGALES</h2>
        </div>
    </div>
</section>
<hr>
<section class="legal">
    <div>
        <div class="title">
            <h3>- Mentions Légales -</h3>
            <img src="../src/img/disclaimer/balance-law-svgrepo-com.svg" alt="logo illustrant une balance de justice">
        </div>
        <p>L’éditeur des sites Internet www.MaisonB.fr est la société SARL dont le siège social est au 126 boulevard serurier 75019 Paris au capital de 150 000 euros immatriculée au Registre du commerce et des sociétés de PARIS sous le numéro RCS 531 550 217.</p>  
        <p>N° de TVA intracommunautaire : FR 145 135 507 121</p>
        <p>Directeur de la publication : François DUPONT</p>
        <p>Tél. : 01 42 08 37 95</p>
        <p>Hébergement du site Internet www.MaisonB.fr réalisé par ONLINE.NET, 8, rue de la Ville L’Evêque, 75008 Paris. Tél. : +33 (0)1 84 13 00 00</p>
    </div>
    <div>
        <div class="title">
            <h3>- Cookies -</h3>
            <img src="../src/img/disclaimer/cookie-svgrepo-com.svg" alt="logo illustrant un cookie">
        </div>
        <p>Finalité des Cookies</p>
        <p>Lors de votre consultation du site MasionB.fr, des informations relatives à votre navigation sont susceptibles d’être enregistrées dans des fichiers “Cookies” installés sur votre terminal (ordinateur, smartphone, tablette, etc.).</p>
        <p>Nous émettons ces cookies dans le but de faciliter votre navigation sur notre site. Ils peuvent également être émis par nos partenaires afin de personnaliser l’offre publicitaire qui vous est adressée en dehors du site MaisonB.fr</p>
        <p>Les cookies émis par MaisonB.fr</p>
        <p>Les cookies que nous installons nous permettent d’identifier votre navigateur lorsque vous vous connectez à notre site MaisonB.fr</p>
        <p>Soucieux d’apporter la meilleure offre de service possible aux utilisateurs du site MaisonB.fr, nous éditons des cookies pour :</p>
        <ul>
            <li>Établir des statistiques de fréquentation (nombre de visites, consultation des pages.. .),</li>
            <li>Optimiser la présentation de notre Site MaisonB.fr eût égard aux préférences d’affichage de votre terminal,</li>
            <li>Fournir à l’utilisateur du contenu en rapport avec ses centres d’intérêt et de personnaliser les offres qui lui sont adressées.</li>
        </ul>
        <p>Les Cookies émis par nos prestataires</p>
        <p>Lorsque vous consultez MaisonB.fr , des cookies édités par nos sociétés prestataires (cookies tiers) sont susceptibles d’être placés dans votre terminal via les pages de notre Site.</p>
        <p>Les cookies déposés par nos prestataires sur le site MaisonB.fr qui visent à promouvoir nos activités et nos offres, ont pour objet :</p>
        <ul>
            <li>D’identifier les produits consultés sur le site MaisonB.fr afin de personnaliser l’offre publicitaire qui vous est adressée pour promouvoir des sites tiers (extérieur au site MaisonB.fr).</li>
            <li>De vous adresser des offres personnalisées par email, (uniquement si vous avez accepté de recevoir des offres de nos partenaires).</li>
            <li>De vous identifier sur notre espace fidélité</li>
            <li>L’émission et l’utilisation de cookies par nos prestataires sont soumises à leur politique de protection de la vie privée. MaisonB.fr n’a ni accès, ni contrôle sur leurs cookies. Toutefois MaisonB.fr veille à ce que ses prestataires traitent les informations collectées sur le Site MaisonB.fr exclusivement pour les besoins de MaisonB.fr et dans le respect de la loi « Informatique et Libertés ».</li>
        </ul>
        <p>Vous pouvez refuser les cookies tiers par un paramétrage appropriés de votre navigateur.</p>
    </div>
    <div>
        <div class="title">
            <h3>- Informatique et Libertés -</h3>
            <img src="../src/img/disclaimer/desktop-svgrepo-com.svg" alt="logo illustrant un ordinateur">
        </div>
        <p>Le site MaisonB.fr est déclaré sous le numéro 1878477 auprès de la Commission Nationale Informatique et Libertés (CNIL) en application de la loi n°78-17 du 6 janvier 1978 modifiée en 2004, relative à l’informatique, aux fichiers et aux libertés. Les informations recueillies font l’objet d’un traitement informatique destiné à la communication d’offres commerciales, d’informations sur les produits et la marque Maison B. Le destinataire des données est la société SARL MaisonB. Conformément à la loi « informatique et libertés », chaque internaute ayant déposé, sur le site MaisonB.fr, des informations nominatives le concernant, bénéficie d’un droit d’accès et de rectification de ces données, qu’il peut exercer en s’adressant à la société : MAISON B : – boulevard Serurier – 75019 Paris.</p>
    </div>
    <div>
        <div class="title">
            <h3>- Garantie et Sécurité -</h3>
            <img src="../src/img/disclaimer/security-svgrepo-com.svg" alt="logo illustrant la sécurité">
        </div>
        <p>Le contenu de ce site est édité sous réserve d’erreurs techniques et/ou typographiques et avec des photos non contractuelles. La responsabilité de la société SARL MaisonB ne saurait donc être engagée quant à l’exactitude des informations mises à disposition des utilisateurs qui accèdent au site. SARL MaisonB ne peut en outre garantir que son fonctionnement sera exempt d’interruptions ou d’erreurs.</p>
    </div>
</section>

