                                            <!--  PAGE D'ACCES AU COTE ADMIN -->
<section class="banner">
            <h2>IDENTIFICATION</h2>
</section>
<hr>
<section class="article2">
    <div>
        <h3>Page reservé aux administrateurs</h3>
        <p>retour à la <a href="?action=home">Page d'accueil</a></p>
    </div>
</section>
<section class="contactUs">
    <form action="?action=login" method="POST">
        <div>
            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required="required">
        </div>
        <div>
            <label for="password">Mot de passe:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div class="error_message">
            <?= $items?>
        </div>
        <div>
            <button type="submit">SE CONNECTER</button>
        </div>
    </form>
</section>