<section class="banner pastryClass_banner">
    <div>
        <h2>NOS ATELIERS</h2>
        <div class="bloc">
            <p><em>Maison B a le plaisir de vous faire partager son univers et vous ouvre les portes de son laboratoire les vendredis soirs tout au long de l’année. Vous apprendrez l’élaboration de desserts ou gâteaux que vous pourrez réaliser chez vous.</em></p>
            <div class="button"><a href="#">Nous contacter</a></div>
        </div>
    </div>
    <img class="img_right" src="../src/img/cours/cours3.png" alt="photo de notre labo special cours de pâtisserie">
</section>
<hr>
<section class="article2">
    <div>
        <h3>Découvrez nos prochaines dates</h3>
        <p>Vous rêvez de faire des desserts comme un vrai chef pâtissier ? Dans une charmante maison du 19ème arrondissement, je vous partage mes meilleurs astuces pour vous aider à comprendre la pâtisserie et découvrir cet univers mystérieux.</p>
        <p><strong>Si vous êtes un petit groupe d'amis mais que ces dates ne vous conviennent pas, contactez-moi pour convenir d'une autre date ensemble !</strong></p>
    </div>
</section>
<section class="cards">
    <!-- <?php //foreach($ as $): ?> -->
    <div class="card">
        <div>
            <img src="" alt="">
        </div>
        <p><strong> Nom de l'atelier</strong></p>
        <p>date de l'atelier</p>
        <p>prix de l'atelier</p>
        <div class="button"><a href="#">Reserver</a></div>
    </div>
    <!-- <?php //endforeach ?> -->
</section>
<section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="#">Nous contacter</a></div>
</section>
