<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <section class="banner pastry_banner">
            <div>
                <h2>LA PATISSERIE</h2>
                <div class="bloc">
                    <p><em>Goût, créativité et qualité : ce sont les trois mots d’ordre qui définissent l’offre sucrée de Maison B. Retrouvez ici nos gâteaux, macarons et confiseries réalisés chaque jour dans notre laboratoire situé à Paris.</em></p>
                    <div class="button"><a href="#">Nous contacter</a></div>
                </div>
            </div>
        <div><img class="img_right" src="../src/img/patisserie/patisserie24.jpg" alt="photo de différentes tartes"></div>
    </section>
    <hr>
    <section class="article2">
        <div>
            <h3>Découvrez notre gamme</h3>
            <p>Nos Chefs pâtissiers explorent les saveurs et les textures à la recherche de l'équilibre parfait des saveurs. Avec le plaisir pour seul guide, leurs créations dévoilent des associations inédites parfois insolites mais définitivement marquantes.</p>
            <p><strong> Pour quelles créations allez-vous succomber ?</strong></p>
        </div>
    </section>
    <section class="grid">

    </section>

    <section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="#">Nous contacter</a></div>
</section>
</body>
