                                                    <!--  PAGE PATISSERIE -->
<section class="banner pastry_banner">
    <div>
        <h2>LA PATISSERIE</h2>
        <div class="bloc">
            <p><em>Goût, créativité et qualité : ce sont les trois mots d’ordre qui définissent l’offre sucrée de Maison B. Retrouvez ici nos gâteaux, macarons et confiseries réalisés chaque jour dans notre laboratoire situé à Paris.</em></p>
            <div class="button"><a href="?action=contactUs">Nous contacter</a></div>
        </div>
    </div>
    <img id="sliderleft" class="img_right" src="./src/img/patisserie/patisserie24.jpg" alt="photo de différentes tartes maisonb" title="les tartes maisonb">
</section>
<hr>
<section class="article2">
    <div>
        <h3>Découvrez notre gamme</h3>
        <p>Nos Chefs pâtissiers explorent les saveurs et les textures à la recherche de l'équilibre parfait des saveurs. Avec le plaisir pour seul guide, leurs créations dévoilent des associations inédites parfois insolites mais définitivement marquantes.</p>
        <p><strong> Pour quelles créations allez-vous succomber ?</strong></p>
    </div>
</section>
 <!--  resuperation des images 'id,url et description' dans la bdd avec la vaiable $items -->
<section class="grid_pastry">
    <?php foreach($items as $item): ?>
        <img class="img<?= $item['id_pastry'] ?> gallery__img" src="<?= $item['url_pastry'] ?>" alt="<?= $item['description_pastry'] ?>" title="<?= $item['description_pastry'] ?>">
    <?php endforeach ?>
</section>
<section class="contact">
    <p>Pour toutes demandes, plus de renseignements ou pour nous donnez votre avis, n'hesitez pas à nous envoyez un message.</p>
    <div class="button right"><a href="?action=contactUs">Nous contacter</a></div>
</section>
