<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Maison B, retrouver au sein de notre boulangerie/patisserie artisanale dans le 19eme arrondissement de Paris du bon pain, des pâtisseries savoureuses et des cours pour patisser comme un chef!">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title>Maison B - Boulangerie/Patisserie Artisanale</title>
    <link rel="stylesheet" href="../src/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Playfair+Display&display=swap" rel="stylesheet">
</head>


<section class="banner">
    <div>
        <div>
            <h2>VOTRE PANIER</h2>
        </div>
    </div>
</section>
<hr>
<section class="article2">
    <div>
        <h3>Réservation</h3>
        <p>Petit récapitulatif de votre commande</p>
        <p><strong>- Un mail de confirmation vous seras envoyé sous 24/48h  -</strong></p>
    </div>
</section>
<section class="contactUs">
    <form action="" method="POST">
        <div>
            <label for="name">Nom & Prénom:</label>
            <input type="text" id="name" name="name">
        </div>
        <div>
            <label for="phone">Téléphone:</label>
            <input type="tel" id="phone" name="phone">
        </div>
        <div>
            <label for="mail">E-mail:</label>
            <input type="email" id="mail" name="mail">
        </div>
        <div>
            <label for="msg">Message:</label>
            <textarea id="msg" name="message"></textarea>
        </div>
        <div>
                <button type="submit">Envoyer</button>
            </div>
    </form>
    <hr>
    <div class="recap">
        <div>
            <strong>
                <p>Nom de la commande</p>
                <p>DATE</p>
                <p>PRIX</p>
                <p>QUANTITE</p>
                <p>- 126 boulevard Serurier 75019 Paris -</p>
            </strong>
            
        </div>
        <div>
            <img src="../src/img/logo_min.png" alt="logo de la boulangerie/pâtisserie" width= "150px">
        </div>
    </div>
</section>

